### ISSUE TITLE
Package mismatch

### ISSUE THREAD

**Issue by cranedroesch** [pennsignals/ACD_helpers#2]
Somehow this package disappears from my conda environments sometimes.  When I went to (re)install, this happens:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/13458532/100155150-bdc7bd00-2e74-11eb-8ea2-54af835cfb2b.png">

Is it just a matter of changing the `requirements.txt`?

**Comment by jlubken** [comment]
Updated both pyproject.toml and setup.py to match.
